name: Replace Headers
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fix-headers:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Python Script
        run: python replace_headers.py
        
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated header fix"
          git push
